name: CI

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'auto: merge development into master'
          body: 'This is an automated pull request to update from branch development'
          labels: 'auto-merge'